---
- hosts: openwrt
  gather_facts: no
  vars_files:
    - vars.yml
  remote_user: root
  roles:
    - gekmihesg.openwrt
  tasks:
    - name: Copy Authorized Keys
      copy:
        src: authorized_keys
        dest: /etc/dropbear/authorized_keys

    - name: Set ROOT Password
      shell: |
        sed -i 's,root:[^:]*,root:{{ root_password }},' "/etc/shadow"

    - name: Set Local Hostname
      lineinfile:
        dest: /etc/hosts
        line: 10.20.30.1      edu.box api.edu.box
        state: present
        create: no

    - name: Replace Banner
      copy:
        src: banner
        dest: /etc/banner

    - name: Revert Pending Changes
      uci:
        command: revert

    - name: Configure Wifi Device
      uci:
        command: set
        key: wireless.radio0
        value:
          type: mac80211
          hwmode: 11g
          channel: auto
          htmode: HT40-

    - name: Configure Wifi Interface
      uci:
        command: section
        config: wireless
        type: wifi-iface
        find_by:
          device: radio0
          mode: ap
        value:
          ssid: 'Edubox-SR{{ sequence_id }}'
          encryption: psk-mixed
          key: '{{ wifi_password }}'

    - name: Configure System Properties
      uci:
        command: set
        key: system.@system[0]
        value:
          hostname: 'Edubox-SR{{ sequence_id }}'
          zonename: Asia/Jakarta
          timezone: WIT-7

    - name: Configure WAN
      uci:
        command: set
        key: network.wan
        value:
          hostname: 'Edubox-SR{{ sequence_id }}'

    - name: Configure LAN
      uci:
        command: set
        key: network.lan
        value:
          hostname: 'Edubox-SR{{ sequence_id }}'
          ipaddr: '10.20.30.254'

    - name: Configure Firewall
      uci:
        command: set
        key: firewall.@zone[1]
        value:
          input: ACCEPT
          forward: ACCEPT

    - name: Apply Changes
      uci:
        command: commit

    - name: Rebooting
      command: reboot

    - name: Wait for server to restart
      local_action:
        module: wait_for
          host=10.20.30.254
          port=22
          delay=10
          timeout=300
