---
- hosts: openwrt
  gather_facts: no
  vars_files:
    - vars.yml
  remote_user: root
  roles:
    - gekmihesg.openwrt
  tasks:
    - name: Copy OpenWRT Image
      command: '{{ openwrt_scp }} image.bin {{ openwrt_user_host|quote }}:/tmp/sysupgrade.bin'
      delegate_to: localhost

    - name: Start Sysupgrade
      nohup:
        command: sysupgrade -q -n /tmp/sysupgrade.bin

    - name: Wait for server to restart
      local_action:
        module: wait_for
          host=10.20.30.254
          port=22
          delay=10
          timeout=700
